import SvgIcon from "./SvgIcon";

export default () => (
  <SvgIcon>
    <line
      x1="44"
      y1="41.5"
      x2="27"
      y2="41.5"
      vectorEffect="non-scaling-stroke"
    />
    <line
      x1="44"
      y1="37.5"
      x2="27"
      y2="37.5"
      vectorEffect="non-scaling-stroke"
    />
    <line
      x1="44"
      y1="33.5"
      x2="38"
      y2="33.5"
      vectorEffect="non-scaling-stroke"
    />
    <line
      x1="44"
      y1="29.5"
      x2="38"
      y2="29.5"
      vectorEffect="non-scaling-stroke"
    />
    <rect
      x="27.5"
      y="29.5"
      width="7"
      height="4"
      vectorEffect="non-scaling-stroke"
    />
  </SvgIcon>
);
